# Generated by Django 4.2.25 on 2025-10-10 06:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.TextField(help_text='Stock Keeping Unit identifier', max_length=100)),
                ('name', models.TextField(help_text='Product name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current product price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category_id', models.UUIDField(blank=True, help_text='Product category reference', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Product creation timestamp')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'indexes': [models.Index(fields=['tenant', 'product_id'], name='products_tenant_product_idx'), models.Index(fields=['tenant', 'sku'], name='products_tenant_sku_idx'), models.Index(fields=['tenant', 'active'], name='products_tenant_active_idx'), models.Index(fields=['category_id'], name='products_category_idx'), models.Index(fields=['created_at'], name='products_created_at_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_tenant_sku'),
        ),
    ]
