# Generated by Django 4.2.25 on 2025-10-14 15:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_tenant_product_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.UUIDField(blank=True, help_text='Customer reference (no FK constraint)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email_snapshot',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name_snapshot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(help_text='External system order identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.UUIDField(help_text='Order reference (no FK constraint)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.UUIDField(help_text='Product reference (no FK constraint)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant'], name='order_items_tenant_idx'),
        ),
    ]
