# Generated by Django 4.2.25 on 2025-10-10 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Customer name', max_length=255)),
                ('email', models.EmailField(help_text='Customer email address', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional customer metadata')),
                ('search_vector', models.TextField(blank=True, help_text='Full-text search vector (simplified for SQLite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Customer creation timestamp')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'indexes': [models.Index(fields=['search_vector'], name='customers_search_vector_idx'), models.Index(fields=['tenant', 'email'], name='customers_tenant_email_idx'), models.Index(fields=['tenant', 'name'], name='customers_tenant_name_idx'), models.Index(fields=['created_at'], name='customers_created_at_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_tenant_customer_email'),
        ),
    ]
