# Generated by Django 4.2.25 on 2025-10-10 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Tenant name', max_length=255)),
                ('api_key_hash', models.TextField(help_text='Hashed API key for authentication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tenant creation timestamp')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['created_at'], name='tenants_created_at_idx'), models.Index(fields=['name'], name='tenants_name_idx')],
            },
        ),
    ]
