# Generated by Django 4.2.25 on 2025-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Adjustment'), ('order', 'Order Fulfillment'), ('receipt', 'Stock Receipt'), ('return', 'Return Processing'), ('adjustment', 'Inventory Adjustment'), ('system', 'System Generated')], help_text='Source of the stock event', max_length=50),
        ),
    ]
