# Generated by Django 4.2.25 on 2025-10-10 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_token', models.TextField(help_text='Unique upload identifier', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manifest', models.JSONField(blank=True, default=dict, help_text='Upload metadata and configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Upload creation timestamp')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingest_uploads', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Ingest Upload',
                'verbose_name_plural': 'Ingest Uploads',
                'db_table': 'ingest_uploads',
            },
        ),
        migrations.CreateModel(
            name='OrderIngestChunk',
            fields=[
                ('chunk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk in the upload')),
                ('checksum', models.TextField(help_text='Data integrity checksum', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('rows', models.PositiveIntegerField(default=0, help_text='Number of rows in this chunk')),
                ('errors_sample', models.JSONField(blank=True, default=list, help_text='Sample of processing errors')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Chunk reception timestamp')),
                ('upload', models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestions.ingestupload')),
            ],
            options={
                'verbose_name': 'Order Ingest Chunk',
                'verbose_name_plural': 'Order Ingest Chunks',
                'db_table': 'order_ingest_chunks',
                'indexes': [models.Index(fields=['upload', 'chunk_index'], name='chunks_upload_index_idx'), models.Index(fields=['status'], name='chunks_status_idx'), models.Index(fields=['received_at'], name='chunks_received_at_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderingestchunk',
            constraint=models.UniqueConstraint(fields=('upload', 'chunk_index'), name='unique_upload_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='ingestupload',
            index=models.Index(fields=['tenant', 'status'], name='ingest_uploads_tenant_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestupload',
            index=models.Index(fields=['upload_token'], name='ingest_uploads_token_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestupload',
            index=models.Index(fields=['created_at'], name='ingest_uploads_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestupload',
            index=models.Index(fields=['last_activity'], name='ingest_uploads_last_act_idx'),
        ),
    ]
