# Generated by Django 4.2.25 on 2025-10-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingestchunk',
            name='content_type',
            field=models.TextField(blank=True, default='application/x-ndjson', help_text='MIME type of the file', null=True),
        ),
        migrations.AddField(
            model_name='orderingestchunk',
            name='file_path',
            field=models.TextField(blank=True, help_text='Path to the uploaded file', null=True),
        ),
    ]
